function [rmdata,rmind,rmes,rmpi,merror,avgrat,medrat,n] = handleData(dataname,errorname,avgratname,medratname)
%{
    This function reads the household data exported from STATA and returns 
    them in 4 matrices (data, indicators, 2 partial insurance parameters). 
    It also reads the second moments of measurement error and the 
    average/median ratios of outcomes.

    Alexandros Theloudis
    -----------------------------------------------------------------------
%}

%   Initial statements:
global T mDir dDir ;

%   Read main data:
cd(strcat(dDir,'/inputs')) ;
mdata = importdata(dataname) ;
mdata = mdata.data;

%   Declare variable position in dataset extracted from Stata:
cl_es           = 	3	;
cl_pi           = 	4	;
cl_drwH         = 	5	;
cl_i_drwH       = 	6	;
cl_drwH2        = 	7	;
cl_i_drwH2      = 	8	;
cl_drwW         = 	9	;
cl_i_drwW       = 	10	;
cl_drwW2        = 	11	;
cl_i_drwW2      = 	12	;
cl_drcons       = 	13	;
cl_i_drcons     = 	14	;
cl_drwH_dreH	= 	15	;
cl_i_drwH_dreH	= 	16	;
cl_drwH_FdreH	= 	17	;
cl_i_drwH_FdreH	= 	18	;
cl_FdrwH_dreH	= 	19	;
cl_i_FdrwH_dreH	= 	20	;
cl_drwW_dreH	= 	21	;
cl_i_drwW_dreH	= 	22	;
cl_drwW_FdreH	= 	23	;
cl_i_drwW_FdreH	=	24	;
cl_FdrwW_dreH	= 	25	;
cl_i_FdrwW_dreH	= 	26	;
cl_drwH_dreW	= 	27	;
cl_i_drwH_dreW	= 	28	;
cl_drwH_FdreW	= 	29	;
cl_i_drwH_FdreW	= 	30	;
cl_FdrwH_dreW	= 	31	;
cl_i_FdrwH_dreW	= 	32	;
cl_drwW_dreW	= 	33	;
cl_i_drwW_dreW	= 	34	;
cl_drwW_FdreW	= 	35	;
cl_i_drwW_FdreW	= 	36	;
cl_FdrwW_dreW	= 	37	;
cl_i_FdrwW_dreW	= 	38	;
cl_dreH_dreH	= 	39	;
cl_i_dreH_dreH	= 	40	;
cl_dreH_FdreH	= 	41	;
cl_i_dreH_FdreH	= 	42	;
cl_dreH_dreW	= 	43	;
cl_i_dreH_dreW	= 	44	;
cl_dreH_FdreW	= 	45	;
cl_i_dreH_FdreW	= 	46	;
cl_FdreH_dreW	= 	47	;
cl_i_FdreH_dreW	= 	48	;
cl_dreW_dreW	= 	49	;
cl_i_dreW_dreW	= 	50	;
cl_dreW_FdreW	= 	51	;
cl_i_dreW_FdreW	= 	52	;
cl_drwH2_FdreH	= 	53	;
cl_i_drwH2_FdreH	= 	54	;
cl_FdrwH2_dreH      = 	55	;
cl_i_FdrwH2_dreH	= 	56	;
cl_drwW2_FdreH      = 	57	;
cl_i_drwW2_FdreH	= 	58	;
cl_FdrwW2_dreH      =	59	;
cl_i_FdrwW2_dreH	= 	60	;
cl_drwH2_FdreW      = 	61	;
cl_i_drwH2_FdreW	= 	62	;
cl_FdrwH2_dreW      = 	63	;
cl_i_FdrwH2_dreW	= 	64	;
cl_drwW2_FdreW      = 	65	;
cl_i_drwW2_FdreW	= 	66	;
cl_FdrwW2_dreW      = 	67	;
cl_i_FdrwW2_dreW	= 	68	;
cl_drwH_FdreH2      = 	69	;
cl_i_drwH_FdreH2	= 	70	;
cl_FdrwH_dreH2      = 	71	;
cl_i_FdrwH_dreH2	= 	72	;
cl_drwW_FdreH2      = 	73	;
cl_i_drwW_FdreH2	= 	74	;
cl_FdrwW_dreH2      = 	75	;
cl_i_FdrwW_dreH2	= 	76	;
cl_drwH_FdreW2      = 	77	;
cl_i_drwH_FdreW2	= 	78	;
cl_FdrwH_dreW2      = 	79	;
cl_i_FdrwH_dreW2	= 	80	;
cl_drwW_FdreW2      = 	81	;
cl_i_drwW_FdreW2	= 	82	;
cl_FdrwW_dreW2      = 	83	;
cl_i_FdrwW_dreW2	= 	84	;
cl_drwH_FdreH_FdreW     = 	85	;
cl_i_drwH_FdreH_FdreW	= 	86	;
cl_FdrwH_dreH_dreW      = 	87	;
cl_i_FdrwH_dreH_dreW	= 	88	;
cl_drwW_FdreH_FdreW     = 	89	;
cl_i_drwW_FdreH_FdreW	= 	90	;
cl_FdrwW_dreH_dreW      = 	91	;
cl_i_FdrwW_dreH_dreW    = 	92	;
cl_drwH_drcons      = 	93	;
cl_i_drwH_drcons	=	94	;
cl_drwH_Fdrcons     = 	95	;
cl_i_drwH_Fdrcons	= 	96	;
cl_FdrwH_drcons     = 	97	;
cl_i_FdrwH_drcons	= 	98	;
cl_drwW_drcons      = 	99	;
cl_i_drwW_drcons	= 	100	;
cl_drwW_Fdrcons     = 	101	;
cl_i_drwW_Fdrcons	= 	102	;
cl_FdrwW_drcons     = 	103	;
cl_i_FdrwW_drcons	= 	104	;
cl_dreH_drcons      = 	105	;
cl_i_dreH_drcons	= 	106	;
cl_dreH_Fdrcons     = 	107	;
cl_i_dreH_Fdrcons	= 	108	;
cl_FdreH_drcons     = 	109	;
cl_i_FdreH_drcons	= 	110	;
cl_dreW_drcons      = 	111	;
cl_i_dreW_drcons	= 	112	;
cl_dreW_Fdrcons     = 	113	;
cl_i_dreW_Fdrcons	= 	114	;
cl_FdreW_drcons     = 	115	;
cl_i_FdreW_drcons	= 	116	;
cl_drcons_drcons	= 	117	;
cl_i_drcons_drcons	= 	118	;
cl_drcons_Fdrcons	= 	119	;
cl_i_drcons_Fdrcons	= 	120	;
cl_drwH2_Fdrcons	= 	121	;
cl_i_drwH2_Fdrcons	= 	122	;
cl_FdrwH2_drcons	= 	123	;
cl_i_FdrwH2_drcons	= 	124	;
cl_drwW2_Fdrcons	= 	125	;
cl_i_drwW2_Fdrcons	= 	126	;
cl_FdrwW2_drcons	= 	127	;
cl_i_FdrwW2_drcons	= 	128	;
cl_drwH_Fdrcons2	=	129	;
cl_i_drwH_Fdrcons2	= 	130	;
cl_FdrwH_drcons2	= 	131	;
cl_i_FdrwH_drcons2	= 	132	;
cl_drwW_Fdrcons2	= 	133	;
cl_i_drwW_Fdrcons2	= 	134	;
cl_FdrwW_drcons2	= 	135	;
cl_i_FdrwW_drcons2	= 	136	;
cl_drwH_FdreH_Fdrcons	= 	137	;
cl_i_drwH_FdreH_Fdrcons	= 	138	;
cl_FdrwH_dreH_drcons	= 	139	;
cl_i_FdrwH_dreH_drcons	= 	140	;
cl_drwW_FdreH_Fdrcons	= 	141	;
cl_i_drwW_FdreH_Fdrcons	= 	142	;
cl_FdrwW_dreH_drcons	= 	143	;
cl_i_FdrwW_dreH_drcons	= 	144	;
cl_drwH_FdreW_Fdrcons	= 	145	;
cl_i_drwH_FdreW_Fdrcons	= 	146	;
cl_FdrwH_dreW_drcons	= 	147	;
cl_i_FdrwH_dreW_drcons	= 	148	;
cl_drwW_FdreW_Fdrcons	= 	149	;
cl_i_drwW_FdreW_Fdrcons	= 	150	;
cl_FdrwW_dreW_drcons	= 	151	;
cl_i_FdrwW_dreW_drcons	= 	152	;

%   Obtain sample sizes, reshape data into usable format:
l = size(mdata) ;
n = l(1)/T ;

rmdata = vertcat(   reshape(mdata(:,cl_drwH),T,n),            ...		
                    reshape(mdata(:,cl_drwH2),T,n),           ...		
                    reshape(mdata(:,cl_drwW),T,n),            ...		
                    reshape(mdata(:,cl_drwW2),T,n),           ...		
                    reshape(mdata(:,cl_drcons),T,n),          ...		
                    reshape(mdata(:,cl_drwH_dreH),T,n),            ...	
                    reshape(mdata(:,cl_drwH_FdreH),T,n),           ...
                    reshape(mdata(:,cl_FdrwH_dreH),T,n),           ...
                    reshape(mdata(:,cl_drwW_dreH),T,n),            ...	
                    reshape(mdata(:,cl_drwW_FdreH),T,n),           ...	
                    reshape(mdata(:,cl_FdrwW_dreH),T,n),           ...	
                    reshape(mdata(:,cl_drwH_dreW),T,n),            ...	
                    reshape(mdata(:,cl_drwH_FdreW),T,n),           ...	
                    reshape(mdata(:,cl_FdrwH_dreW),T,n),           ...	
                    reshape(mdata(:,cl_drwW_dreW),T,n),            ...	
                    reshape(mdata(:,cl_drwW_FdreW),T,n),           ...	
                    reshape(mdata(:,cl_FdrwW_dreW),T,n),           ...	
                    reshape(mdata(:,cl_dreH_dreH),T,n),            ...
                    reshape(mdata(:,cl_dreH_FdreH),T,n),           ...
                    reshape(mdata(:,cl_dreH_dreW),T,n),            ...
                    reshape(mdata(:,cl_dreH_FdreW),T,n),           ...	
                    reshape(mdata(:,cl_FdreH_dreW),T,n),           ...	
                    reshape(mdata(:,cl_dreW_dreW),T,n),            ...	
                    reshape(mdata(:,cl_dreW_FdreW),T,n),           ...	
                    reshape(mdata(:,cl_drwH2_FdreH),T,n),          ...
                    reshape(mdata(:,cl_FdrwH2_dreH),T,n),          ...		
                    reshape(mdata(:,cl_drwW2_FdreH),T,n),          ...	
                    reshape(mdata(:,cl_FdrwW2_dreH),T,n),          ...		
                    reshape(mdata(:,cl_drwH2_FdreW),T,n),          ...		
                    reshape(mdata(:,cl_FdrwH2_dreW),T,n),          ...		
                    reshape(mdata(:,cl_drwW2_FdreW),T,n),          ...		
                    reshape(mdata(:,cl_FdrwW2_dreW),T,n),          ...		
                    reshape(mdata(:,cl_drwH_FdreH2),T,n),          ...		
                    reshape(mdata(:,cl_FdrwH_dreH2),T,n),          ...		
                    reshape(mdata(:,cl_drwW_FdreH2),T,n),          ...		
                    reshape(mdata(:,cl_FdrwW_dreH2),T,n),          ...		
                    reshape(mdata(:,cl_drwH_FdreW2),T,n),          ...		
                    reshape(mdata(:,cl_FdrwH_dreW2),T,n),          ...		
                    reshape(mdata(:,cl_drwW_FdreW2),T,n),          ...		
                    reshape(mdata(:,cl_FdrwW_dreW2),T,n),          ...		
                    reshape(mdata(:,cl_drwH_FdreH_FdreW),T,n),     ...		
                    reshape(mdata(:,cl_FdrwH_dreH_dreW),T,n),      ...		
                    reshape(mdata(:,cl_drwW_FdreH_FdreW),T,n),     ...		
                    reshape(mdata(:,cl_FdrwW_dreH_dreW),T,n),      ...		
                    reshape(mdata(:,cl_drwH_drcons),T,n),          ...	
                    reshape(mdata(:,cl_drwH_Fdrcons),T,n),           ...		
                    reshape(mdata(:,cl_FdrwH_drcons),T,n),           ...		
                    reshape(mdata(:,cl_drwW_drcons),T,n),            ...		
                    reshape(mdata(:,cl_drwW_Fdrcons),T,n),           ...	
                    reshape(mdata(:,cl_FdrwW_drcons),T,n),           ...		
                    reshape(mdata(:,cl_dreH_drcons),T,n),            ...		
                    reshape(mdata(:,cl_dreH_Fdrcons),T,n),           ...		
                    reshape(mdata(:,cl_FdreH_drcons),T,n),           ...		
                    reshape(mdata(:,cl_dreW_drcons),T,n),            ...		
                    reshape(mdata(:,cl_dreW_Fdrcons),T,n),           ...		
                    reshape(mdata(:,cl_FdreW_drcons),T,n),           ...		
                    reshape(mdata(:,cl_drcons_drcons),T,n),          ...		
                    reshape(mdata(:,cl_drcons_Fdrcons),T,n),         ...		
                    reshape(mdata(:,cl_drwH2_Fdrcons),T,n),          ...	
                    reshape(mdata(:,cl_FdrwH2_drcons),T,n),          ...		
                    reshape(mdata(:,cl_drwW2_Fdrcons),T,n),          ...		
                    reshape(mdata(:,cl_FdrwW2_drcons),T,n),          ...		
                    reshape(mdata(:,cl_drwH_Fdrcons2),T,n),          ...		
                    reshape(mdata(:,cl_FdrwH_drcons2),T,n),          ...		
                    reshape(mdata(:,cl_drwW_Fdrcons2),T,n),          ...
                    reshape(mdata(:,cl_FdrwW_drcons2),T,n),          ...
                    reshape(mdata(:,cl_drwH_FdreH_Fdrcons),T,n),     ...
                    reshape(mdata(:,cl_FdrwH_dreH_drcons),T,n),      ...
                    reshape(mdata(:,cl_drwW_FdreH_Fdrcons),T,n),     ...
                    reshape(mdata(:,cl_FdrwW_dreH_drcons),T,n),      ...
                    reshape(mdata(:,cl_drwH_FdreW_Fdrcons),T,n),     ...
                    reshape(mdata(:,cl_FdrwH_dreW_drcons),T,n),      ...
                    reshape(mdata(:,cl_drwW_FdreW_Fdrcons),T,n),     ...
                    reshape(mdata(:,cl_FdrwW_dreW_drcons),T,n)) ;
rmind  = vertcat(   reshape(mdata(:,cl_i_drwH),T,n),            ...		
                    reshape(mdata(:,cl_i_drwH2),T,n),           ...		
                    reshape(mdata(:,cl_i_drwW),T,n),            ...		
                    reshape(mdata(:,cl_i_drwW2),T,n),           ...		
                    reshape(mdata(:,cl_i_drcons),T,n),          ...		
                    reshape(mdata(:,cl_i_drwH_dreH),T,n),            ...	
                    reshape(mdata(:,cl_i_drwH_FdreH),T,n),           ...
                    reshape(mdata(:,cl_i_FdrwH_dreH),T,n),           ...
                    reshape(mdata(:,cl_i_drwW_dreH),T,n),            ...	
                    reshape(mdata(:,cl_i_drwW_FdreH),T,n),           ...	
                    reshape(mdata(:,cl_i_FdrwW_dreH),T,n),           ...	
                    reshape(mdata(:,cl_i_drwH_dreW),T,n),            ...	
                    reshape(mdata(:,cl_i_drwH_FdreW),T,n),           ...	
                    reshape(mdata(:,cl_i_FdrwH_dreW),T,n),           ...	
                    reshape(mdata(:,cl_i_drwW_dreW),T,n),            ...	
                    reshape(mdata(:,cl_i_drwW_FdreW),T,n),           ...	
                    reshape(mdata(:,cl_i_FdrwW_dreW),T,n),           ...	
                    reshape(mdata(:,cl_i_dreH_dreH),T,n),            ...
                    reshape(mdata(:,cl_i_dreH_FdreH),T,n),           ...
                    reshape(mdata(:,cl_i_dreH_dreW),T,n),            ...
                    reshape(mdata(:,cl_i_dreH_FdreW),T,n),           ...	
                    reshape(mdata(:,cl_i_FdreH_dreW),T,n),           ...	
                    reshape(mdata(:,cl_i_dreW_dreW),T,n),            ...	
                    reshape(mdata(:,cl_i_dreW_FdreW),T,n),           ...	
                    reshape(mdata(:,cl_i_drwH2_FdreH),T,n),          ...
                    reshape(mdata(:,cl_i_FdrwH2_dreH),T,n),          ...		
                    reshape(mdata(:,cl_i_drwW2_FdreH),T,n),          ...	
                    reshape(mdata(:,cl_i_FdrwW2_dreH),T,n),          ...		
                    reshape(mdata(:,cl_i_drwH2_FdreW),T,n),          ...		
                    reshape(mdata(:,cl_i_FdrwH2_dreW),T,n),          ...		
                    reshape(mdata(:,cl_i_drwW2_FdreW),T,n),          ...		
                    reshape(mdata(:,cl_i_FdrwW2_dreW),T,n),          ...		
                    reshape(mdata(:,cl_i_drwH_FdreH2),T,n),          ...		
                    reshape(mdata(:,cl_i_FdrwH_dreH2),T,n),          ...		
                    reshape(mdata(:,cl_i_drwW_FdreH2),T,n),          ...		
                    reshape(mdata(:,cl_i_FdrwW_dreH2),T,n),          ...		
                    reshape(mdata(:,cl_i_drwH_FdreW2),T,n),          ...		
                    reshape(mdata(:,cl_i_FdrwH_dreW2),T,n),          ...		
                    reshape(mdata(:,cl_i_drwW_FdreW2),T,n),          ...		
                    reshape(mdata(:,cl_i_FdrwW_dreW2),T,n),          ...		
                    reshape(mdata(:,cl_i_drwH_FdreH_FdreW),T,n),     ...		
                    reshape(mdata(:,cl_i_FdrwH_dreH_dreW),T,n),      ...		
                    reshape(mdata(:,cl_i_drwW_FdreH_FdreW),T,n),     ...		
                    reshape(mdata(:,cl_i_FdrwW_dreH_dreW),T,n),      ...		
                    reshape(mdata(:,cl_i_drwH_drcons),T,n),          ...	
                    reshape(mdata(:,cl_i_drwH_Fdrcons),T,n),           ...		
                    reshape(mdata(:,cl_i_FdrwH_drcons),T,n),           ...		
                    reshape(mdata(:,cl_i_drwW_drcons),T,n),            ...		
                    reshape(mdata(:,cl_i_drwW_Fdrcons),T,n),           ...	
                    reshape(mdata(:,cl_i_FdrwW_drcons),T,n),           ...		
                    reshape(mdata(:,cl_i_dreH_drcons),T,n),            ...		
                    reshape(mdata(:,cl_i_dreH_Fdrcons),T,n),           ...		
                    reshape(mdata(:,cl_i_FdreH_drcons),T,n),           ...		
                    reshape(mdata(:,cl_i_dreW_drcons),T,n),            ...		
                    reshape(mdata(:,cl_i_dreW_Fdrcons),T,n),           ...		
                    reshape(mdata(:,cl_i_FdreW_drcons),T,n),           ...		
                    reshape(mdata(:,cl_i_drcons_drcons),T,n),          ...		
                    reshape(mdata(:,cl_i_drcons_Fdrcons),T,n),         ...		
                    reshape(mdata(:,cl_i_drwH2_Fdrcons),T,n),          ...	
                    reshape(mdata(:,cl_i_FdrwH2_drcons),T,n),          ...		
                    reshape(mdata(:,cl_i_drwW2_Fdrcons),T,n),          ...		
                    reshape(mdata(:,cl_i_FdrwW2_drcons),T,n),          ...		
                    reshape(mdata(:,cl_i_drwH_Fdrcons2),T,n),          ...		
                    reshape(mdata(:,cl_i_FdrwH_drcons2),T,n),          ...		
                    reshape(mdata(:,cl_i_drwW_Fdrcons2),T,n),          ...
                    reshape(mdata(:,cl_i_FdrwW_drcons2),T,n),          ...
                    reshape(mdata(:,cl_i_drwH_FdreH_Fdrcons),T,n),     ...
                    reshape(mdata(:,cl_i_FdrwH_dreH_drcons),T,n),      ...
                    reshape(mdata(:,cl_i_drwW_FdreH_Fdrcons),T,n),     ...
                    reshape(mdata(:,cl_i_FdrwW_dreH_drcons),T,n),      ...
                    reshape(mdata(:,cl_i_drwH_FdreW_Fdrcons),T,n),     ...
                    reshape(mdata(:,cl_i_FdrwH_dreW_drcons),T,n),      ...
                    reshape(mdata(:,cl_i_drwW_FdreW_Fdrcons),T,n),     ...
                    reshape(mdata(:,cl_i_FdrwW_dreW_drcons),T,n));

%   Extract partial insurance parameters:
rmes = reshape(mdata(:,cl_es),T,n) ;  % matrix of es_it
rmpi = reshape(mdata(:,cl_pi),T,n) ;  % matrix of pi_it

%   Extract masurement error. In the 6-column 7-row matrix:
%   -> 1st column: m.error in head wages
%   -> 2nd column: m.error in wife wages
%   -> 3rd column: m.error in head earnings
%   -> 4th column: m.error in wife earnings
%   -> 5th column: m.error in head wages-earnings covariance
%   -> 6th column: m.error in wife wages-earnings covariance
%   Each row corresponds to a PSID year (1999-2011).
merror = importdata(errorname) ;
merror = merror.data ;
merror = merror(:,2:7) ;

%   Ratios of consumption and earnings:
if isempty(avgratname)==1       % bootstrap for wages does not need this
    avgrat = [] ;
else
    avgrat = importdata(avgratname) ;
    avgrat = avgrat.data ;
end
if isempty(medratname)==1       % wealthy & robust subsamples do not use median ratios
    medrat = [] ;
else
    medrat = importdata(medratname) ;
    medrat = medrat.data ;
end

%   Return to working directory:
cd(mDir) ;

end