function [mMATCHED,mBPS] = fit_empirical_model_wk(mC, mCD, merrC, sT)
%{  
    This function estimates the moments in the simulated data generated by 
    the quantitative model; these are the moments used in the covariance
    matrix estimation of the quasi-reduced form model.

    Alexandros Theloudis
    -----------------------------------------------------------------------
%}


%%  1.  INITIALIZE OBJECTS
%   Initialize vectors to hold empirical moments
%   -----------------------------------------------------------------------

%   Vectors to hold matched empirical moments under preferred specification:

%   Wages second moments:
%   matrix 11: E[DwH DwH]
mom_wHwH    = zeros(sT,1) ;     
mom_wHwH_a  = zeros(sT,1) ;
%   matrix 13: E[DwH DwW] 
mom_wHwW    = zeros(sT,1) ;
mom_wHwW_a  = zeros(sT,1) ;
mom_wHwW_b  = zeros(sT,1) ;
%   matrix 33: E[DwW DwW]   
mom_wWwW    = zeros(sT,1) ;
mom_wWwW_a  = zeros(sT,1) ;

%   Wage-earnings/consumption second moments:
%   matrix 15: E[DwH DyH]      
mom_wHyH_a = NaN(sT,1) ;
mom_wHyH_b = NaN(sT,1) ;
%   matrix 35: E[DwW DyH]
mom_wWyH_a = NaN(sT,1) ;
mom_wWyH_b = NaN(sT,1) ;
%   matrix 17: E[DwH DyW]
mom_wHyW_a = NaN(sT,1) ;
mom_wHyW_b = NaN(sT,1) ;
%   matrix 37: E[DwW DyW]       
mom_wWyW_a = NaN(sT,1) ; 
mom_wWyW_b = NaN(sT,1) ; 
%   matrix 19: E[DwH Dc]
mom_wHc_a  = NaN(sT,1) ;
mom_wHc_b  = NaN(sT,1) ;
%   matrix 39: E[DwW Dc] 
mom_wWc_a  = NaN(sT,1) ;
mom_wWc_b  = NaN(sT,1) ; 

%   Earnings & consumption second moments:
%   matrix 55: E[DyH DyH]
mom_yHyH_a  = NaN(sT,1) ;
%   matrix 57: E[DyH DyW]
mom_yHyW_a  = NaN(sT,1) ;
mom_yHyW_b  = NaN(sT,1) ;
%   matrix 77: E[DyW DyW]  
mom_yWyW_a  = NaN(sT,1) ;
%   matrix 59: E[DyH Dc] 	
mom_yHc_a  = NaN(sT,1) ;
mom_yHc_b  = NaN(sT,1) ;
%   matrix 79: E[DyW Dc]   
mom_yWc_a  = NaN(sT,1) ;
mom_yWc_b  = NaN(sT,1) ;
%   matrix 99: E[Dc Dc]	
mom_cc_a   = NaN(sT,1) ;

%   Vectors to hold BPS empirical moments (contemporaneous covariances):
mom_wHyH = NaN(sT,1) ;
%   matrix 35: E[DwW DyH]
mom_wWyH = NaN(sT,1) ;  
%   matrix 17: E[DwH DyW]
mom_wHyW = NaN(sT,1) ;
%   matrix 37: E[DwW DyW]
mom_wWyW = NaN(sT,1) ; 
%   matrix 19: E[DwH Dc]
mom_wHc  = NaN(sT,1) ;
%   matrix 39: E[DwW Dc]
mom_wWc  = NaN(sT,1) ;
 %   matrix 55: E[DyH DyH]
mom_yHyH = NaN(sT,1) ;
%   matrix 57: E[DyH DyW]
mom_yHyW = NaN(sT,1) ;
%   matrix 77: E[DyW DyW]
mom_yWyW = NaN(sT,1) ;
%   matrix 59: E[DyH Dc]
mom_yHc  = NaN(sT,1) ;
%   matrix 79: E[DyW Dc]
mom_yWc  = NaN(sT,1) ;
%   matrix 99: E[Dc Dc]
mom_cc   = NaN(sT,1) ;


%%  2.  MATCHED EMPIRICAL MOMENTS
%   Construct vector of moments E(data_moment_i)
%   -----------------------------------------------------------------------

%   Matrix 11: E[DwH DwH]   
%   -----------------------------------------------------------------------

%   Variances:
j = 2 ;
while j <= sT-1  
    mom_wHwH(j) = ((mC(j,:).*mC(j,:)) - merrC(j,1) - merrC(j-1,1)) * mCD(j,:)' ;
    mom_wHwH(j) = mom_wHwH(j) / (mCD(j,:)*mCD(j,:)') ;
    j = j + 1 ;
end 

%   Intertemporal covariances:
j = 2 ;
while j <= sT
    mom_wHwH_a(j) = ((mC(j,:).*mC(j-1,:)) + merrC(j-1,1)) * (mCD(j,:).*mCD(j-1,:))' ;
    mom_wHwH_a(j) = mom_wHwH_a(j) / (mCD(j,:)*mCD(j-1,:)') ;
    j = j + 1 ;
end

%   Matrix 13: E[DwH DwW]   
%   -----------------------------------------------------------------------

%   Auto-covariances:
j = 2 ;
while j <= sT-1
	mom_wHwW(j) = ((mC(j,:).*mC(2*sT+j,:))) * (mCD(j,:).*mCD(2*sT+j,:))' ;
    mom_wHwW(j) = mom_wHwW(j) / (mCD(j,:)*mCD(2*sT+j,:)') ;
	j = j + 1 ;
end
    
%   Intertemporal covariances:
j = 2 ;
while j <= sT 
    mom_wHwW_a(j) = ((mC(j-1,:).*mC(2*sT+j,:))) * (mCD(j-1,:).*mCD(2*sT+j,:))' ;
    mom_wHwW_a(j) = mom_wHwW_a(j) / (mCD(j-1,:)*mCD(2*sT+j,:)') ;
	j = j + 1 ;
end

j = 2 ;
while j <= sT 
	mom_wHwW_b(j) = ((mC(j,:).*mC(2*sT+j-1,:))) * (mCD(j,:).*mCD(2*sT+j-1,:))' ; 
    mom_wHwW_b(j) = mom_wHwW_b(j) / (mCD(j,:)*mCD(2*sT+j-1,:)') ;
	j = j + 1 ;
end

%   Matrix 33: E[DwW DwW]   
%   -----------------------------------------------------------------------

%   Variances:
j = 2 ;
while j <= sT-1
    mom_wWwW(j) = ((mC(2*sT+j,:).*mC(2*sT+j,:)) - merrC(j,2) - merrC(j-1,2)) * mCD(2*sT+j,:)' ;
    mom_wWwW(j) = mom_wWwW(j) / (mCD(2*sT+j,:)*mCD(2*sT+j,:)') ;
    j = j + 1 ;
end 
    
%   Intertemporal covariances:
j = 2 ;
while j <= sT
    mom_wWwW_a(j) = ((mC(2*sT+j,:).*mC(2*sT+j-1,:)) + merrC(j-1,2)) * (mCD(2*sT+j,:).*mCD(2*sT+j-1,:))' ;
    mom_wWwW_a(j) = mom_wWwW_a(j) / (mCD(2*sT+j,:)*mCD(2*sT+j-1,:)') ;
    j = j + 1 ;
end
    

%   Matrix 15: E[DwH DyH]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1) 
    mom_wHyH(j) = (mC(5*sT+j,:) - merrC(j,5) - merrC(j-1,5)) * mCD(5*sT+j,:)' ;
    mom_wHyH(j) = mom_wHyH(j) / sum(mCD(5*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal covariances:
j = 2 ;
while j <= sT
    mom_wHyH_a(j) = (mC(6*sT+j-1,:) + merrC(j-1,5)) * mCD(6*sT+j-1,:)' ;
    mom_wHyH_a(j) = mom_wHyH_a(j) / sum(mCD(6*sT+j-1,:)) ;
	j = j + 1 ;
end

j = 2 ;
while j <= sT 
    mom_wHyH_b(j) = (mC(7*sT+j-1,:) + merrC(j-1,5)) * mCD(7*sT+j-1,:)' ;
    mom_wHyH_b(j) = mom_wHyH_b(j) / sum(mCD(7*sT+j-1,:)) ;
	j = j + 1 ;
end

%   Matrix 35: E[DwW DyH]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1) 
    mom_wWyH(j) = mC(8*sT+j,:) * mCD(8*sT+j,:)' ;
    mom_wWyH(j) = mom_wWyH(j) / sum(mCD(8*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal covariances:
j = 2 ;
while j <= sT 
    mom_wWyH_a(j) = mC(9*sT+j-1,:) * mCD(9*sT+j-1,:)' ;
    mom_wWyH_a(j) = mom_wWyH_a(j) / sum(mCD(9*sT+j-1,:)) ;
	j = j + 1 ;
end

j = 2 ;
while j <= sT
    mom_wWyH_b(j) = mC(10*sT+j-1,:) * mCD(10*sT+j-1,:)' ;
    mom_wWyH_b(j) = mom_wWyH_b(j) / sum(mCD(10*sT+j-1,:)) ;
	j = j + 1 ;
end

%   Matrix 17: E[DwH DyW]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1) 
    mom_wHyW(j) = mC(11*sT+j,:) * mCD(11*sT+j,:)' ; 
    mom_wHyW(j) = mom_wHyW(j) / sum(mCD(11*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal covariances:
j = 2 ;
while j <= sT 
	mom_wHyW_a(j) = mC(12*sT+j-1,:) * mCD(12*sT+j-1,:)' ; 
    mom_wHyW_a(j) = mom_wHyW_a(j) / sum(mCD(12*sT+j-1,:)) ;
	j = j + 1 ;
end

j = 2 ;
while j <= sT 
    mom_wHyW_b(j) = mC(13*sT+j-1,:) * mCD(13*sT+j-1,:)' ;
    mom_wHyW_b(j) = mom_wHyW_b(j) / sum(mCD(13*sT+j-1,:)) ;
	j = j + 1 ;
end

%   Matrix 37: E[DwW DyW]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1) 
    mom_wWyW(j) = (mC(14*sT+j,:) - merrC(j,6) - merrC(j-1,6)) * mCD(14*sT+j,:)' ;
    mom_wWyW(j) = mom_wWyW(j) / sum(mCD(14*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal covariances:
j = 2 ;
while j <= sT 
	mom_wWyW_a(j) = (mC(15*sT+j-1,:) + merrC(j-1,6)) * mCD(15*sT+j-1,:)' ;
    mom_wWyW_a(j) = mom_wWyW_a(j) / sum(mCD(15*sT+j-1,:)) ;
	j = j + 1 ;
end

j = 2 ;
while j <= sT 
	mom_wWyW_b(j) = (mC(16*sT+j-1,:) + merrC(j-1,6)) * mCD(16*sT+j-1,:)' ;
    mom_wWyW_b(j) = mom_wWyW_b(j) / sum(mCD(16*sT+j-1,:)) ;
	j = j + 1 ;
end

%   Matrix 19: E[DwH Dc]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1)
    mom_wHc(j) = mC(44*sT+j,:) * mCD(44*sT+j,:)' ;
    mom_wHc(j) = mom_wHc(j) / sum(mCD(44*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal covariances:
j = 2 ;
while j <= sT 
	mom_wHc_a(j) = mC(45*sT+j-1,:) * mCD(45*sT+j-1,:)' ;
    mom_wHc_a(j) = mom_wHc_a(j) / sum(mCD(45*sT+j-1,:)) ;
	j = j + 1 ;
end

j = 2 ;
while j <= sT
	mom_wHc_b(j) = mC(46*sT+j-1,:) * mCD(46*sT+j-1,:)' ;
    mom_wHc_b(j) = mom_wHc_b(j) / sum(mCD(46*sT+j-1,:)) ;
	j = j + 1 ;
end

%   Matrix 39: E[DwW Dc]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1) 
    mom_wWc(j) = mC(47*sT+j,:) * mCD(47*sT+j,:)' ;
    mom_wWc(j) = mom_wWc(j) / sum(mCD(47*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal covariances:
j = 2 ;
while j <= sT 
	mom_wWc_a(j) = mC(48*sT+j-1,:) * mCD(48*sT+j-1,:)' ;
    mom_wWc_a(j) = mom_wWc_a(j) / sum(mCD(48*sT+j-1,:)) ;
	j = j + 1 ;
end

j = 2 ;
while j <= sT
	mom_wWc_b(j) = mC(49*sT+j-1,:) * mCD(49*sT+j-1,:)' ;
    mom_wWc_b(j) = mom_wWc_b(j) / sum(mCD(49*sT+j-1,:)) ;
	j = j + 1 ;
end

%   Matrix 55: E[DyH DyH]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1) 
    mom_yHyH(j) = (mC(17*sT+j,:) - merrC(j,3) - merrC(j-1,3)) * mCD(17*sT+j,:)' ;
    mom_yHyH(j) = mom_yHyH(j) / sum(mCD(17*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal co-variances:
j = 2 ;
while j <= sT 
	mom_yHyH_a(j) = (mC(18*sT+j-1,:) + merrC(j-1,3)) * mCD(18*sT+j-1,:)' ;
    mom_yHyH_a(j) = mom_yHyH_a(j) / sum(mCD(18*sT+j-1,:)) ;
	j = j + 1 ;
end


%   Matrix 57: E[DyH DyW]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1) 
    mom_yHyW(j) = mC(19*sT+j,:) * mCD(19*sT+j,:)' ; 
    mom_yHyW(j) = mom_yHyW(j) / sum(mCD(19*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal co-variances:
j = 2 ;
while j <= sT
	mom_yHyW_a(j) = mC(20*sT+j-1,:) * mCD(20*sT+j-1,:)' ; 
    mom_yHyW_a(j) = mom_yHyW_a(j) / sum(mCD(20*sT+j-1,:)) ;
	j = j + 1 ;
end

j = 2 ;
while j <= sT
	mom_yHyW_b(j) = mC(21*sT+j-1,:) * mCD(21*sT+j-1,:)' ;
    mom_yHyW_b(j) = mom_yHyW_b(j) / sum(mCD(21*sT+j-1,:)) ;
	j = j + 1 ;
end


%   Matrix 77: E[DyW DyW]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1) 
    mom_yWyW(j) = (mC(22*sT+j,:) - merrC(j,4) - merrC(j-1,4)) * mCD(22*sT+j,:)' ;
    mom_yWyW(j) = mom_yWyW(j) / sum(mCD(22*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal covariances:
j = 2 ;
while j <= sT 
	mom_yWyW_a(j) = (mC(23*sT+j-1,:) + merrC(j-1,4))* mCD(23*sT+j-1,:)' ;
    mom_yWyW_a(j) = mom_yWyW_a(j) / sum(mCD(23*sT+j-1,:)) ;
	j = j + 1 ;
end

%   Matrix 59: E[DyH Dc]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1) 
    mom_yHc(j) = mC(50*sT+j,:) * mCD(50*sT+j,:)' ;
    mom_yHc(j) = mom_yHc(j) / sum(mCD(50*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal covariances:
j = 2 ;
while j <= sT 
	mom_yHc_a(j) = mC(51*sT+j-1,:) * mCD(51*sT+j-1,:)' ;
    mom_yHc_a(j) = mom_yHc_a(j) / sum(mCD(51*sT+j-1,:)) ;
	j = j + 1 ;
end

j = 2 ;
while j <= sT 
	mom_yHc_b(j) = mC(52*sT+j-1,:) * mCD(52*sT+j-1,:)' ; 
    mom_yHc_b(j) = mom_yHc_b(j) / sum(mCD(52*sT+j-1,:)) ;
	j = j + 1 ;
end

%   Matrix 79: E[DyW Dc]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1) 
    mom_yWc(j) = mC(53*sT+j,:) * mCD(53*sT+j,:)' ; 
    mom_yWc(j) = mom_yWc(j) / sum(mCD(53*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal co-variances:
j = 2 ;
while j <= sT 
	mom_yWc_a(j) = mC(54*sT+j-1,:) * mCD(54*sT+j-1,:)' ; 
    mom_yWc_a(j) = mom_yWc_a(j) / sum(mCD(54*sT+j-1,:)) ;
	j = j + 1 ;
end

j = 2 ;
while j <= sT
	mom_yWc_b(j) = mC(55*sT+j-1,:) * mCD(55*sT+j-1,:)' ; 
    mom_yWc_b(j) = mom_yWc_b(j) / sum(mCD(55*sT+j-1,:)) ;
	j = j + 1 ;
end

%   Matrix 99: E[Dc Dc]   
%   -----------------------------------------------------------------------

%   Contemporaneous covariance:
j = 2 ;
while j <= (sT-1) 
    mom_cc(j) = mC(56*sT+j,:) * mCD(56*sT+j,:)' ;
    mom_cc(j) = mom_cc(j) / sum(mCD(56*sT+j,:)) ;
    j = j + 1 ;
end

%   Intertemporal covariances:
j = 2 ;
while j <= sT
	mom_cc_a(j) = mC(57*sT+j-1,:) * mCD(57*sT+j-1,:)' ;
    mom_cc_a(j) = mom_cc_a(j) / sum(mCD(57*sT+j-1,:)) ;
	j = j + 1 ;
end


%%  3.  DELIVER VECTORS OF EMPIRICAL MOMENTS
%   Stack and deliver vectors of moments
%   -----------------------------------------------------------------------

%   Stack moments together:
mMATCHED = [mean(mom_wHwH(2:sT-1))           ; ...  % 1        
            mean(mom_wHwH_a(2:sT))           ; ...  % 2  
            mean(mom_wHwW(2:sT-1))           ; ...  % 3    
            mean(mom_wHwW_a(2:sT))           ; ...  % 4  
            mean(mom_wHwW_b(2:sT))           ; ...  % 5  
            mean(mom_wWwW(2:sT-1))           ; ...  % 6    
            mean(mom_wWwW_a(2:sT))           ; ...  % 7    
            mean(mom_wHyH_a(2:sT))           ; ...  % 8
            mean(mom_wHyH_b(2:sT))           ; ...  % 9
            mean(mom_wWyH_a(2:sT))           ; ...  % 10
            mean(mom_wWyH_b(2:sT))           ; ...  % 11
            mean(mom_wHyW_a(2:sT))           ; ...  % 12
            mean(mom_wHyW_b(2:sT))           ; ...  % 13
            mean(mom_wWyW_a(2:sT))           ; ...  % 14
            mean(mom_wWyW_b(2:sT))           ; ...  % 15
            mean(mom_wHc_a(2:sT))            ; ...  % 16
            mean(mom_wHc_b(2:sT))            ; ...  % 17
            mean(mom_wWc_a(2:sT))            ; ...  % 18
            mean(mom_wWc_b(2:sT))            ; ...  % 19 
            mean(mom_yHyH_a(2:sT))           ; ...  % 20
            mean(mom_yHyW_a(2:sT))           ; ...  % 21
            mean(mom_yHyW_b(2:sT))           ; ...  % 22
            mean(mom_yWyW_a(2:sT))           ; ...  % 23
            mean(mom_yHc_a(2:sT))            ; ...  % 24
            mean(mom_yHc_b(2:sT))            ; ...  % 25
            mean(mom_yWc_a(2:sT))            ; ...  % 26
            mean(mom_yWc_b(2:sT))            ; ...  % 27
            mean(mom_cc_a(2:sT))]            ;      % 28
mBPS =  [   mean(mom_wHyH(2:sT-1))           ; ...  % 1
            mean(mom_wWyH(2:sT-1))           ; ...  % 2
            mean(mom_wHyW(2:sT-1))           ; ...  % 3
            mean(mom_wWyW(2:sT-1))           ; ...  % 4
            mean(mom_wHc(2:sT-1))            ; ...  % 5
            mean(mom_wWc(2:sT-1))            ; ...  % 6
            mean(mom_yHyH(2:sT-1))           ; ...  % 7
            mean(mom_yHyW(2:sT-1))           ; ...  % 8
            mean(mom_yWyW(2:sT-1))           ; ...  % 9
            mean(mom_yHc(2:sT-1))            ; ...  % 10
            mean(mom_yWc(2:sT-1))            ; ...  % 11
            mean(mom_cc(2:sT-1))]            ;      % 12
end